server:
  port: 8080

spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/springBoot
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#国际化文件指定位置、顺序, 其主要是为了方便在properties中定义错误信息,这个顺序是引用的顺序
  messages:
    basename: i18n/ValidationMessageszh_CN,i18n/ValidationMessagesen,i18n/ValidationMessages